require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TCC' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'GVRSDK'
  pod 'CTPanoramaView', :git => 'https://github.com/cristianoccazinsp/CTPanoramaView.git', :branch => 'control-both'

  pod 'react-native-background-downloader', :path => '../node_modules/react-native-background-downloader'

  target 'TCCTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'TCC-tvOS' do
  # Pods for TCC-tvOS

  target 'TCC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
